function Get-DistroNexusWorkspaceSavePreview { [CmdletBinding()] param([Parameter(Mandatory)]$Definition,[Parameter(Mandatory)][Int64]$ExpectedRevision) Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.save.preview.v1' -Payload @{ Definition=$Definition; ExpectedRevision=$ExpectedRevision } }
function Save-DistroNexusWorkspace { [CmdletBinding(SupportsShouldProcess)] param([Parameter(Mandatory)][ValidatePattern('^[A-Fa-f0-9]{64}$')][string]$PreviewToken) if ($PSCmdlet.ShouldProcess('reviewed workspace','Save workspace')) { Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.save.execute.v1' -Payload @{ PreviewToken=$PreviewToken } } }
function Get-DistroNexusWorkspaceDuplicatePreview { [CmdletBinding()] param([Parameter(Mandatory)][Guid]$Id,[Parameter(Mandatory)][string]$Name,[Parameter(Mandatory)][Int64]$ExpectedRevision) Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.duplicate.preview.v1' -Payload @{ Id=$Id; Name=$Name; ExpectedRevision=$ExpectedRevision } }
function Copy-DistroNexusWorkspace { [CmdletBinding(SupportsShouldProcess)] param([Parameter(Mandatory)][ValidatePattern('^[A-Fa-f0-9]{64}$')][string]$PreviewToken) if ($PSCmdlet.ShouldProcess('reviewed workspace','Duplicate workspace')) { Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.duplicate.execute.v1' -Payload @{ PreviewToken=$PreviewToken } } }
function Get-DistroNexusWorkspaceRemovePreview { [CmdletBinding()] param([Parameter(Mandatory)][Guid]$Id,[Parameter(Mandatory)][Int64]$ExpectedRevision) Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.remove.preview.v1' -Payload @{ Id=$Id; ExpectedRevision=$ExpectedRevision } }
function Remove-DistroNexusWorkspace { [CmdletBinding(SupportsShouldProcess,ConfirmImpact='High')] param([Parameter(Mandatory)][ValidatePattern('^[A-Fa-f0-9]{64}$')][string]$PreviewToken) if ($PSCmdlet.ShouldProcess('reviewed workspace','Remove workspace')) { Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.remove.execute.v1' -Payload @{ PreviewToken=$PreviewToken } | Out-Null } }
function Get-DistroNexusWorkspaceImportPreview { [CmdletBinding()] param([Parameter(Mandatory)][ValidateLength(1,524288)][string]$Content) Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.import.preview.v1' -Payload @{ Content=$Content } }
function Import-DistroNexusWorkspace { [CmdletBinding(SupportsShouldProcess)] param([Parameter(Mandatory)][ValidatePattern('^[A-Fa-f0-9]{64}$')][string]$PreviewToken) if ($PSCmdlet.ShouldProcess('reviewed workspace content','Import workspace as untrusted')) { Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.import.execute.v1' -Payload @{ PreviewToken=$PreviewToken } } }
function Get-DistroNexusWorkspaceExportPreview { [CmdletBinding()] param([Parameter(Mandatory)][Guid]$Id,[Parameter(Mandatory)][Int64]$ExpectedRevision) Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.export.preview.v1' -Payload @{ Id=$Id; ExpectedRevision=$ExpectedRevision } }
function Get-DistroNexusWorkspaceTrustPreview { [CmdletBinding()] param([Parameter(Mandatory)][Guid]$Id,[Parameter(Mandatory)][Int64]$ExpectedRevision) Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.trust.preview.v1' -Payload @{ Id=$Id; ExpectedRevision=$ExpectedRevision } }
function Approve-DistroNexusWorkspaceTrust { [CmdletBinding(SupportsShouldProcess,ConfirmImpact='High')] param([Parameter(Mandatory)][ValidatePattern('^[A-Fa-f0-9]{64}$')][string]$PreviewToken) if ($PSCmdlet.ShouldProcess('reviewed workspace','Approve workspace trust')) { Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.trust.execute.v1' -Payload @{ PreviewToken=$PreviewToken } } }
function Get-DistroNexusWorkspaceLaunchPreview { [CmdletBinding()] param([Parameter(Mandatory)][Guid]$Id) Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.launch.preview.v1' -Payload @{ Id=$Id } }
function Invoke-DistroNexusWorkspace { [CmdletBinding(SupportsShouldProcess,ConfirmImpact='High')] param([Parameter(Mandatory)][ValidatePattern('^[A-Fa-f0-9]{64}$')][string]$PreviewToken) if ($PSCmdlet.ShouldProcess('reviewed workspace','Launch workspace')) { Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.launch.execute.v1' -Payload @{ PreviewToken=$PreviewToken } } }
function Get-DistroNexusWorkspaceRetryPreview { [CmdletBinding()] param([Parameter(Mandatory)][Guid]$Id,[Parameter(Mandatory)][Guid]$ActionId) Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.retry.preview.v1' -Payload @{ Id=$Id; ActionId=$ActionId } }
function Retry-DistroNexusWorkspaceAction { [CmdletBinding(SupportsShouldProcess,ConfirmImpact='High')] param([Parameter(Mandatory)][ValidatePattern('^[A-Fa-f0-9]{64}$')][string]$PreviewToken) if ($PSCmdlet.ShouldProcess('reviewed workspace action','Retry workspace action')) { Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.retry.execute.v1' -Payload @{ PreviewToken=$PreviewToken } } }
function Get-DistroNexusWorkspaceClosePreview { [CmdletBinding()] param([Parameter(Mandatory)][Guid]$Id) Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.close.preview.v1' -Payload @{ Id=$Id } }
function Close-DistroNexusWorkspace { [CmdletBinding(SupportsShouldProcess)] param([Parameter(Mandatory)][ValidatePattern('^[A-Fa-f0-9]{64}$')][string]$PreviewToken) if ($PSCmdlet.ShouldProcess('reviewed workspace','Close workspace')) { Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.close.execute.v1' -Payload @{ PreviewToken=$PreviewToken } } }
function Get-DistroNexusWorkspaceOperation { [CmdletBinding()] param([Parameter(Mandatory)][ValidatePattern('^[A-Fa-f0-9]{64}$')][string]$OperationId) Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.operation.status.v1' -Payload @{ OperationId=$OperationId } }
function Stop-DistroNexusWorkspaceOperation { [CmdletBinding(SupportsShouldProcess)] param([Parameter(Mandatory)][ValidatePattern('^[A-Fa-f0-9]{64}$')][string]$OperationId) if ($PSCmdlet.ShouldProcess($OperationId,'Request workspace operation cancellation')) { Invoke-DistroNexusWorkspaceBridge -Operation 'workspace.cancel.v1' -Payload @{ OperationId=$OperationId } } }
function New-DistroNexusWorkspace { [CmdletBinding(SupportsShouldProcess)] param([Parameter(Mandatory)]$Definition,[Parameter(Mandatory)][Int64]$ExpectedRevision) $preview=Get-DistroNexusWorkspaceSavePreview -Definition $Definition -ExpectedRevision $ExpectedRevision; if($PSCmdlet.ShouldProcess('reviewed workspace','Create workspace')) { Save-DistroNexusWorkspace -PreviewToken $preview.PreviewToken -Confirm:$false } else { $preview } }
function Set-DistroNexusWorkspace { [CmdletBinding(SupportsShouldProcess)] param([Parameter(Mandatory)]$Definition,[Parameter(Mandatory)][Int64]$ExpectedRevision) $preview=Get-DistroNexusWorkspaceSavePreview -Definition $Definition -ExpectedRevision $ExpectedRevision; if($PSCmdlet.ShouldProcess('reviewed workspace','Save workspace')) { Save-DistroNexusWorkspace -PreviewToken $preview.PreviewToken -Confirm:$false } else { $preview } }
function Get-DistroNexusWorkspaceActionRetryPreview { [CmdletBinding()] param([Parameter(Mandatory)][Guid]$Id,[Parameter(Mandatory)][Guid]$ActionId) Get-DistroNexusWorkspaceRetryPreview -Id $Id -ActionId $ActionId }
