$resxPath = "d:\wsl\DistroNexus\src\Client\DistroNexus.Desktop\Properties\Resources.resx"
$designerPath = "d:\wsl\DistroNexus\src\Client\DistroNexus.Desktop\Properties\Resources.Designer.cs"

[xml]$resx = Get-Content $resxPath

$sb = New-Object System.Text.StringBuilder

$sb.AppendLine("//------------------------------------------------------------------------------") | Out-Null
$sb.AppendLine("// <auto-generated>") | Out-Null
$sb.AppendLine("//     This code was generated by a tool.") | Out-Null
$sb.AppendLine("//") | Out-Null
$sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if") | Out-Null
$sb.AppendLine("//     the code is regenerated.") | Out-Null
$sb.AppendLine("// </auto-generated>") | Out-Null
$sb.AppendLine("//------------------------------------------------------------------------------") | Out-Null
$sb.AppendLine("") | Out-Null
$sb.AppendLine("namespace DistroNexus.Desktop.Properties {") | Out-Null
$sb.AppendLine("    using System;") | Out-Null
$sb.AppendLine("    ") | Out-Null
$sb.AppendLine("    ") | Out-Null
$sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(`"System.Resources.Tools.StronglyTypedResourceBuilder`", `"17.0.0.0`")]") | Out-Null
$sb.AppendLine("    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]") | Out-Null
$sb.AppendLine("    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]") | Out-Null
$sb.AppendLine("    public class Resources {") | Out-Null
$sb.AppendLine("        ") | Out-Null
$sb.AppendLine("        private static global::System.Resources.ResourceManager resourceMan;") | Out-Null
$sb.AppendLine("        ") | Out-Null
$sb.AppendLine("        private static global::System.Globalization.CultureInfo resourceCulture;") | Out-Null
$sb.AppendLine("        ") | Out-Null
$sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(`"Microsoft.Performance`", `"CA1811:AvoidUncalledPrivateCode`")]") | Out-Null
$sb.AppendLine("        internal Resources() {") | Out-Null
$sb.AppendLine("        }") | Out-Null
$sb.AppendLine("        ") | Out-Null
$sb.AppendLine("        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]") | Out-Null
$sb.AppendLine("        public static global::System.Resources.ResourceManager ResourceManager {") | Out-Null
$sb.AppendLine("            get {") | Out-Null
$sb.AppendLine("                if (object.ReferenceEquals(resourceMan, null)) {") | Out-Null
$sb.AppendLine("                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(`"DistroNexus.Desktop.Properties.Resources`", typeof(Resources).Assembly);") | Out-Null
$sb.AppendLine("                    resourceMan = temp;") | Out-Null
$sb.AppendLine("                }") | Out-Null
$sb.AppendLine("                return resourceMan;") | Out-Null
$sb.AppendLine("            }") | Out-Null
$sb.AppendLine("        }") | Out-Null
$sb.AppendLine("        ") | Out-Null
$sb.AppendLine("        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]") | Out-Null
$sb.AppendLine("        public static global::System.Globalization.CultureInfo Culture {") | Out-Null
$sb.AppendLine("            get {") | Out-Null
$sb.AppendLine("                return resourceCulture;") | Out-Null
$sb.AppendLine("            }") | Out-Null
$sb.AppendLine("            set {") | Out-Null
$sb.AppendLine("                resourceCulture = value;") | Out-Null
$sb.AppendLine("            }") | Out-Null
$sb.AppendLine("        }") | Out-Null

foreach ($data in $resx.root.data) {
    if ($data.type -ne $null) { continue } # Skip non-string resources if any
    $name = $data.name
    $safeName = $name -replace " ", "_"
    
    $sb.AppendLine("        ") | Out-Null
    $sb.AppendLine("        public static string $safeName {") | Out-Null
    $sb.AppendLine("            get {") | Out-Null
    $sb.AppendLine("                return ResourceManager.GetString(`"$name`", resourceCulture);") | Out-Null
    $sb.AppendLine("            }") | Out-Null
    $sb.AppendLine("        }") | Out-Null
}

$sb.AppendLine("    }") | Out-Null
$sb.AppendLine("}") | Out-Null

$sb.ToString() | Set-Content $designerPath -Encoding UTF8
Write-Host "Resources.Designer.cs updated."