
$resxFile = "$PSScriptRoot\..\src\Client\DistroNexus.Desktop\Properties\Resources.resx"
$designerFile = "$PSScriptRoot\..\src\Client\DistroNexus.Desktop\Properties\Resources.Designer.cs"
$namespace = "DistroNexus.Desktop.Properties"
$className = "Resources"

if (-not (Test-Path $resxFile)) {
    Write-Error "Resx file not found: $resxFile"
    exit 1
}

[xml]$resxXml = Get-Content $resxFile

$properties = ""
foreach ($node in $resxXml.root.data) {
    if ($node.name) {
        $name = $node.name
        $properties += @"
        
        /// <summary>
        ///   Looks up a localized string similar to $name.
        /// </summary>
        public static string $name {
            get {
                return ResourceManager.GetString("$name", resourceCulture);
            }
        }
"@
    }
}

$header = @"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $namespace {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class $className {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal $className() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("$namespace.$className", typeof($className).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
"@

$footer = @"
    }
}
"@

$content = $header + $properties + "`n" + $footer
Set-Content -Path $designerFile -Value $content -Encoding UTF8
Write-Host "Updated $designerFile"
